import Header from "@/components/header/header";
import "./globals.css";

import localFont from "next/font/local";
import Footer from "@/components/footer/footer";

const satoshi = localFont({
  src: [
    {
      path: "./font/Satoshi-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./font/Satoshi-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./font/Satoshi-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./font/Satoshi-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata = {
  title: "lucas.design",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={satoshi.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
